### ISSUE TITLE
Fix WP_Error check for videos

### ISSUE THREAD

**Issue by swissspidy** [brashrebel/wptv#6]
In the `display` method there's a check if `$videos` is of type `WP_Error`. However, this will probably never be the case as the request result is run through `json_decode`. This function returns `null` on failure.

**Comment by brashrebel** [comment]
Thanks @swissspidy ! Oversight on my part for sure. I'll fix that.

**Comment by brashrebel** [comment]
This has been fixed.

**Comment by swissspidy** [comment]
Nope, doesn't look like.

On line 66 there's still the `is_wp_error` check, but `wp_remote_retrieve_body` never returns a `WP_Error` object.

**Comment by brashrebel** [comment]
Crap. You're right. I was thinking of something else and didn't really check. Will fix in next commit.
